Copyright = "All rights reserved - 2015"
DisqusShortname = "yo_0"
LanguageCode = "fr-FR"
Title = "Awesome content for web dev"
baseurl = "https://mymk.github.io/"
canonifyurls = true
paginate = 5
theme = "casper"
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/"
weight = -120
[params]
RSSLink = "http://feeds.feedburner.com/"
author = "MYMK"
authorlocation = "Limoges, France"
authorwebsite = "https://github.com/mymk"
bio = "French freelance collective"
cover = "/forestryio/images/subtle-gaussian-blur-wallpaper-1698-1791-hd-wallpapers.jpg"
description = "Curated content for human"
githubName = "mymk"
googleAnalyticsUserID = ""
hideHUGOSupport = true
logo = "/forestryio/images/mymk.jpg"
twitterName = "mymk"
