---
upload_path: "/forestryio/images"
frontmatter_file_url_template: images
body_file_url_template: ''
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
  post:
    default_front_matter_template: post
version: '0.17'
